name: flappwrite_stripe
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  appwrite: ^4.0.1
  flutter:
    sdk: flutter
  flutter_stripe: ^2.4.0
  flutter_riverpod: ^1.0.3
  flutter_svg: ^1.0.3
  url_launcher: ^6.1.0
  appwrite_auth_kit: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/

  
  
  
  
  
  
  
  
  
  
