name: flappwrite_stripe
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  appwrite: ^4.0.1
  flutter:
    sdk: flutter
  flutter_stripe: ^2.4.0
  flappwrite_account_kit:
    git: https://github.com/lohanidamodar/flappwrite_account_kit

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^1.0.0





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
